layout_spectrum: 0.1415771
color:
  saturation: 0.6039426
  brandStrength: 0.3924222
  lightness: 0.7688172
  rhythmicContrast: 0.5627605
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
typography_spectrum: 0.5340502
name: terrytyelee
