name: terrytyelee
favicon: null
layout_spectrum: 0.1415771
typography_spectrum: 0.13505
title: part time prophet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3924222
  lightness: 0.7688172
  saturation: 0.6039426
  rhythmicContrast: 0.5627605
purpose: []
