name: terrytyelee
favicon: null
layout_spectrum: 0
typography_spectrum: 0.14525
title: tye da songsmith
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#44403d'
    - '#fefefe'
    - '#c6c3be'
    - '#97948f'
  brandStrength: 0.9375
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
