name: terrytyelee
favicon: null
layout_spectrum: 0.41314
typography_spectrum: 0.19366
title: terrytyelee
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#44403d'
    - '#fefefe'
    - '#c6c3be'
    - '#97948f'
  brandStrength: 0.625
  lightness: 0.1953405
  saturation: 0.2168459
  rhythmicContrast: 0.2885305
purpose: []
